# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='loc_id',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True),
        ),
    ]
