# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0016_auto_20171025_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='marker_template',
            field=models.TextField(blank=True, help_text='The Underscore.js template to render for showing popup\n        information about a marker on the map'),
        ),
        migrations.AlterField(
            model_name='changeset',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changesets', to='proposal.Proposal'),
        ),
        migrations.AlterField(
            model_name='document',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='proposal.Proposal'),
        ),
        migrations.AlterField(
            model_name='image',
            name='document',
            field=models.ForeignKey(help_text='Source document for image', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='proposal.Document'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='region_name',
            field=models.CharField(blank=True, help_text='Used when filtering layers by\n                                   region name', max_length=128),
        ),
        migrations.AlterField(
            model_name='layer',
            name='url',
            field=models.URLField(help_text='URL of the GeoJSON representing the\n        layer geometry.\n        '),
        ),
    ]
