# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-14 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0017_auto_20171212_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='importer',
            name='timezone',
            field=models.CharField(default='US/Eastern', help_text='Ambiguous date fields will be\n                                interpreted as having this timezone', max_length=25),
        ),
    ]
